### ISSUE TITLE
fluentd image doesn't process the sub-second portion of timestamps for docker logs

### ISSUE THREAD

**Issue by toidi** [SumoLogic/fluentd-output-sumologic#1]
Same issue as https://github.com/kubernetes/kubernetes/issues/21480

**Comment by stevezau** [comment]
Hi @toidi,

This repo contains the fluentd addon not an image? What image are you referring to?

The plugin tries to parse out the miliseconds epoch https://github.com/SumoLogic/fluentd-output-sumologic/blob/master/lib/fluent/plugin/out_sumologic.rb#L105

**Comment by toidi** [comment]
Hey @stevezau,

I'm referring to https://github.com/SumoLogic/fluentd-kubernetes-sumologic and `sumologic/fluentd-kubernetes-sumologic:latest` image.

Our tests showed - plugin doesn't provide sub second timestamp resolution.

**Comment by stevezau** [comment]
Hey @toidi hmm it's probably best to create an issue there as i'm not sure it's related to this plugin.

It seems it's also set there tho https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/master/conf.d/source.containers.conf#L7

Do you have an example log i can see? Maybe one working from logstash vs this one? Feel free to email if you don't want to post them here. or ping me on slack via http://slack.sumologic.com

**Comment by toidi** [comment]
It is easy to reproduce.

I just followed instruction https://github.com/SumoLogic/fluentd-kubernetes-sumologic
and result was like on the screenshot.

<img width="202" alt="screen shot 2017-01-05 at 14 32 14" src="https://cloud.githubusercontent.com/assets/892861/22013357/9dc9b86c-dca9-11e6-9083-a8100371066e.png">

@stevezau you are right. I might choose wrong repo for this issue.
