### ISSUE TITLE
Migrate to use v0.14 API?

### ISSUE THREAD

**Issue by waderobson** [SumoLogic/fluentd-output-sumologic#11]
Hi, I'm wondering if there are plans to migrate this plugin to the new API? It would be great to get the millisecond support working and it would also allow for the use of tag_parts in the config. 

It would allow me to do something like this
`source_category "Dev/${tag_parts[0]}/${tag_parts[1]}"`

Thanks

**Comment by frankreno** [comment]
This has been resolved by a recent pr and is available in https://rubygems.org/gems/fluent-plugin-sumologic_output/versions/1.0.0.  Both features are now available.
