### ISSUE TITLE
Multi-line processing

### ISSUE THREAD

**Issue by smitty4x4** [SumoLogic/fluentd-output-sumologic#13]
Unless I'm missing something, multi-line processing doesn't seem to exist. Any way to get this functionality?
The plugin works great otherwise...tagging and sending messages to http endpoint is a breeze.

**Comment by frankreno** [comment]
@smitty4x4 - at the moment, this is just an output plugin to send data to Sumo.  We wanted to keep it simple and leave multiline processing upstream.  However, you can pair this with the FluentD Concat plugin to handle these scenarios.  We do this in our Kubernetes FluentD Plugin.

https://github.com/fluent-plugins-nursery/fluent-plugin-concat

**Comment by frankreno** [comment]
resolving as this should be left upstream
