### ISSUE TITLE
source_name vs source

### ISSUE THREAD

**Issue by nlundbo** [SumoLogic/fluentd-output-sumologic#18]
Hello,
I have a question regarding the use of `source_name` vs `source`(does not exist, but maybe should).

In the example provided in readme it seem to be used to put things like a `service-name`, but looking at sumologic documentation `source_name` is used for file-names (source_name mapping to _sourceName).
 
For me it would make sense to use the `source`(_source) for this type of data, but this is not available in this plugin.

Could someone elaborate on this? Perhaps this boils down to some limitation of the http API.

I'm thinking these things eventually affect indexing of of some sort on SumoLogic side.

Thanks :)

Ref: https://help.sumologic.com/Search/Get-Started-with-Search/Search-Basics/Search-Metadata

**Comment by frankreno** [comment]
@nlundbo - apologies for the delay here.  Since this uses our HTTP source, we do not have the ability to update the source, only the source name.
