### ISSUE TITLE
Version 1.0.0 spewing errors about "cannot load such file -- fluent/plugin/output"

### ISSUE THREAD

**Issue by glitchsys** [SumoLogic/fluentd-output-sumologic#19]
So we were using version 0.0.4 of the plugin but recently installed 1.0.0 of the plugin.  Using the same config, when we started td-agent it began spewing out hundreds of messages a minute in the td-agent.log file, eventually filling up the disk.

This is my config: I had to change < to [  due to formatting issues, but it's correct in my actual config.   
<pre>
  ## Send to Sumologic - Catchall HTTP endpoint ##
  [store>
    @type forest
    subtype sumologic
    escape_tag_separator /
    [template>
      endpoint https://endpoint2.collection.us2.sumologic.com/receiver/v1/http/Zablahblahblahblah9gliErQ==
      log_format json
      verify_ssl true
      source_host ${hostname}
      source_name prodb
      source_category prod/${escaped_tag}
    [/template>
  [/store>
</pre>

And this was what showed up in the logs over and over again:

<pre>
/opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/buffer.rb:193:in `emit'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/output.rb:593:in `block in emit'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/output.rb:592:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/output.rb:592:in `emit'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/output.rb:42:in `next'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/buffer.rb:199:in `block in emit'
/opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/buffer.rb:193:in `emit'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/output.rb:593:in `block in emit'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/output.rb:592:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/output.rb:592:in `emit'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/output.rb:42:in `next'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin/out_copy.rb:78:in `emit'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/event_router.rb:90:in `emit_stream'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/event_router.rb:81:in `emit'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:177:in `block in log_event_loop'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:175:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:175:in `log_event_loop'
2017-11-09 20:38:46 +0000 [error]: Cannot output messages with tag 'fluent.error'
2017-11-09 20:38:46 +0000 [error]: failed to configure/start sub output sumologic: cannot load such file -- fluent/plugin/output
2017-11-09 20:38:46 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sumologic_output-1.0.0/lib/fluent/plugin/out_sumologic.rb:1:in `<top (required)>'
/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:172:in `block in try_load_plugin'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:170:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:170:in `try_load_plugin'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:130:in `new_impl'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/plugin.rb:59:in `new_output'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-forest-0.3.3/lib/fluent/plugin/out_forest.rb:131:in `block in plant'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-forest-0.3.3/lib/fluent/plugin/out_forest.rb:128:in `synchronize'
</pre>

The above configuration works perfectly fine using version 0.0.4 of the sumologic pluugin.

**Comment by hoegertn** [comment]
The latest version `1.0.0` is not compatible with fluentd 0.12. That is why the number was increased. td-agent is using fluentd 0.12

You should be able to use version `0.0.7` with td-agent.

**Comment by frankreno** [comment]
Thank you @hoegertn, @glitchsys that is correct you need to use `0.0.7` with td-agent.  Going to close this.

**Comment by ervansetiawan** [comment]
Just FYI, I found that 0.0.5 is the latest working version to be used with td-agent. I believe the change to use 0.14 API in 0.0.6 broke the compatibility with the td-agent.
