### ISSUE TITLE
Adding timestamp to logs - why?

### ISSUE THREAD

**Issue by nlundbo** [SumoLogic/fluentd-output-sumologic#20]
Hi,
I noticed that in the code this plugin is adding a 'timestamp' to all emitted logs. Why is this?
In our case we happen to use the identifier 'timestamp' for our usecase - which made this extra confusing.

The implementation is also broken in the sense that is uses :timestamp in the merge-operation.
:timestamp will never be == "timestamp", so the merge-operation will have two keys "timestamp" if you merge and then marshal a json object already containing a field "timestamp" (technically  valid JSON - but really not what you want).

Depending on how the ingestion and billing is performed on the SumoLogic side - this could increase cost for the customers.

**Comment by frankreno** [comment]
fixed by https://github.com/SumoLogic/fluentd-output-sumologic/pull/27.  Available in 1.0.2.
