### ISSUE TITLE
Interpolation inside _sumo_metadata

### ISSUE THREAD

**Issue by yangmillstheory** [SumoLogic/fluentd-output-sumologic#24]
Using the Docker logging driver for NGINX, values in `_sumo_metadata` is interpolated.

```
<filter nginx>
  @type record_transformer
  <record>
    logger.sumo true
    logger.s3   true
    _sumo_metadata {
      "host": "#{ENV['SUMO_HOST']}",
      "source": "${!container_id}",
      "category": "foo/${!tag}/${!source}"
    }
  </record>
</filter>
```

In logs, "host" is the hardcoded string `#{ENV['SUMO_HOST']}`.

**Comment by frankreno** [comment]
This was either fixed at some point or perhaps something else is happening, but this works fine and we have a unit test that tests this and is passing.
