### ISSUE TITLE
JSON timestamp problem

### ISSUE THREAD

**Issue by Trane9991** [SumoLogic/fluentd-output-sumologic#4]
Hello,
I have golang application, and I'm using Logrus lib, with JSON formatter.
This lib creates JSON with next format:
```
{"level":"error","msg":"Wrong message type","time":"2017-03-17T15:33:58Z"}
```
When I'm giving this JSON messages to the FluentD, on the sumologic then I see next log:
```
{
    "timestamp":2017000,
    "level":"error",
    "msg":"Wrong message type"
}
```

If I disabled timestamp from my logs, everything works ok. 
There is should be a better way to workaround this.

Thank you.

**Comment by frankreno** [comment]
@Trane9991 : are you still seeing this issue?

**Comment by Trane9991** [comment]
Yes, in order to avoid the issue we are generating our own UNIX timestamps with the JSON key "ts", and pointed fluentd configuration to use the "ts" key as the timestamp.
```
  format json
  time_key ts
```

This way it works fine.
