### ISSUE TITLE
Sumologic app settings for multi-line

### ISSUE THREAD

**Issue by davidhao3300** [SumoLogic/fluentd-output-sumologic#41]
I'm having trouble getting Sumologic and fluentd-kubernetes-sumologic library to cooperate for multi-line messages.

I use a custom multiline start regexp (/\d{2}:\d{2}:\d{2}/, matches any hh:mm:ss timestamp in the log message). When I start running the daemonset in Kubernetes, I noticed that Sumologic wasn't respecting the multiline-batching done by the plugin. I fiddled around with some of the HTTP collector settings, and this is what I found:
(Reference doc: https://help.sumologic.com/03Send-Data/Sources/04Reference-Information-for-Sources/Collecting-Multiline-Logs)

Let's say for the case where we have the following records to be sent to sumologic:
```
{"log": "00:00:00 message1\n00:00 submessage1"}
{"log": "00:00:01 message2\nsubmessage2"}
```

**Using the default settings ("Detect messages spanning multiple lines" checked and "Infer Boundaries" checked):**
The multiline grouping done in the plugin is ignored. It feels like Sumologic is taking the batch of messages sent from this plugin, concatenating them all together, and then doing its own multiline boundary processing.
```
00:00:00 message1
---
00:00 submessage1
---
00:00:01 message2
submessage2
```

**"Detect messages spanning multiple lines" checked and "Boundary Regex" set to my regex  (/\d{2}:\d{2}:\d{2}/)):**
This works, but also defeats the purpose of the concat plugin. Ideally the concat plugin would do all of the work for multiline grouping, and sumologic would just respect it.
```
00:00:00 message1
00:00 submessage1
---
00:00:01 message2
submessage2
```

**"Detect messages spanning multiple lines" unchecked and "Enable One Message Per Request" checked:**
This causes all the messages in a batch request to get smushed together into one message in the Sumologic UI.
```
00:00:00 message1
00:00 submessage1
00:00:01 message2
submessage2
```

**"Detect messages spanning multiple lines" unchecked and "Enable One Message Per Request" unchecked:**
When everything is disabled, the multiline grouping is ignored, and instead any newline will cause a new message.
```
00:00:00 message1
---
00:00submessage1
---
00:00:01 message2
---
submessage2
```

I believe that concat plugin used by the library works fine (I stubbed out the call to this library with the stdout output plugin, and it correctly logs the concatenated logs based on the regex), which is why I'm filing an issue in this repo instead of fluentd-kubernetes-sumologic.

If you believe that I should contact the Sumologic main support channel to ask them about their API behavior, just let me know and I'll reach out to them. I figured I could be missing something obvious since I would expect someone else to have filed an issue by now if there was really a multi-line issue.

**Comment by bin3377** [comment]
I assume you are using `log_format` == `text`
Under this model, the concat plugin is actually useless since the json(e.g. record) wrapper will be stripped before sending.  
So the payload actually sent to sumologic as: 
```
00:00:00 message1⤶
00:00 submessage1⤶
00:00:01 message2⤶
submessage2
```
(⤶ for newline e.g. `\n`)
That's why you can only depends on "Boundary RegEx" to do the multiline detection again on sumo side.
If possible, sending your message in `json` format will be a better choice if you want concat plugin works

**Comment by davidhao3300** [comment]
Ah, that's a good point, let me give that a shot. Thanks!
Yeah, I had a feeling that something like that may have happened, but I wasn't familiar enough with Ruby/fluentd setup to verify that the payload was like that.

**Comment by davidhao3300** [comment]
Yeah, I confirmed that the following steps seem to work, for anyone who comes across the issue:
- Make sure log format is set to "json" (we overrode the default value, I didn't notice)
- Disable both boundary detection and "One message per request" for the HTTP Collector
We had the additional need that we keep the original log message format (not the JSON outputted from this plugin) for legacy reasons, so adding a field extractor `json "log" as _raw` matching the collector seems to work.

Thank you for the help!

**Comment by davidhao3300** [comment]
It would be nice to somehow warn (in docs or in an app log) that multiline doesn't really work with the text log format
