### ISSUE TITLE
1.4.1 broke parameter expansion of `${tag_parts[1]}`

### ISSUE THREAD

**Issue by Trane9991** [SumoLogic/fluentd-output-sumologic#47]
Hello.
I'm using the plugin with next configuration:
```
<match {app,ecs}.**>
 @type           sumologic
 endpoint        "#{ENV["SUMOLOGIC_ENDPOINT"]}"
 log_format      json
 source_category "#{ENV["SUMOLOGIC_SOURCE_CATEGORY"]}"
 source_name     ${tag_parts[1]} # use second part of the tag as source_name
 open_timeout    300
</match>
```

Yesterday I upgraded to the v1.4.1 and placeholder expansion for `${tag_parts[1]}` stopped working. PR #40 broke it, now `${tag[1]}` has to be used. Not a big problem for me, but I think you should mention somewhere that this is breaking change.

**Comment by bin3377** [comment]
Thanks for the reporting! Will take a look if we need a fix or an update of document

**Comment by bin3377** [comment]
https://github.com/SumoLogic/fluentd-output-sumologic/pull/48

**Comment by Trane9991** [comment]
@bin3377 thanks!
What do you think about mentioning this breaking change in the [CHANGELOG.md](https://github.com/SumoLogic/fluentd-output-sumologic/blob/master/CHANGELOG.md#change-log)?
Entry for the v1.4.1 completely missing there.

**Comment by bin3377** [comment]
updated.
But consider we are moving the release to be fully managed by TravisCI. I may consider remove the CHANGELOG.md later (since it's duplicated with the release note) or somehow make it automatically updated.

**Comment by asafpelegcodes** [comment]
I didn't understand the outcome from this?

Is this something that is going to be fixed or is it an intended change?

**Comment by asafpelegcodes** [comment]
NVM I figured it out, thanks
