### ISSUE TITLE
unknow key errors

### ISSUE THREAD

**Issue by yfractal** [SumoLogic/fluentd-output-sumologic#80]
After setting this plugin, it will generate `Unknown key: SameSite = None`

Detail is in https://github.com/fluent/fluentd-docker-image/issues/240

**Comment by yfractal** [comment]
I guess, the error should come from this

https://github.com/nahi/httpclient/blob/4658227a46f7caa633ef8036f073bbd1f0a955a2/lib/httpclient/webagent-cookie.rb#L203

And from this [reply](https://github.com/fluent/fluentd-docker-image/issues/240#issuecomment-1142292690), we can know, set `disable_cookies` to `true` can fix this.

**Comment by sumo-drosiek** [comment]
Hi @yfractal

Yes, you can disable cookies. Cookies are coming from AWS ELB and we do not use it in order to process data.

Here is related upstream issue (about warnings), but it doesn't look to be fixed anytime soon: https://github.com/nahi/httpclient/issues/415
