### ISSUE TITLE
Access record in `custom_fields`

### ISSUE THREAD

**Issue by tmbull** [SumoLogic/fluentd-output-sumologic#81]
Hello, I would like to know if it is possible to extract some field from the record and add the value as a custom field. For example: 

```
        custom_fields "pod=${record['kubernetes']['pod_name']}"
```

If the record contains this:

```
{
  "log": "01:22:42.462  DEBUG hello world",
  "stream": "stdout",
  "kubernetes": {
    "pod_name": "my-pod-659698dfb9-smslh"
    }
  }
}
```

The value `my-pod-659698dfb9-smslh` would be included as a custom field named `pod`. 

If there's another way to do this in fluentd, please let me know. I'm relatively new to fluentd as well. Thanks for the plugin!

**Comment by swiatekm-sumo** [comment]
Hey @tmbull, you can set this via standard FluentD filters. The fields are kept inside the `_sumo_metadata.fields` key in the record. This field is a string containing a comma-separated list of `key=value` statements. For example, for your example with the pod name, you would do:

```
<filter **>
  @type record_modifier
  <record>
    _sumo_metadata ${record["_sumo_metadata"][:fields] = record["_sumo_metadata"].fetch(:fields, "").split(",").append("pod_name=#{record['kubernetes']['pod_name']}").join(","); record["_sumo_metadata"]}
  </record>
</filter>
```

That's quite the mouthful, so we also have a plugin that does this (and some other stuff) for you here: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/tree/main/fluent-plugin-kubernetes-sumologic.

**Comment by tmbull** [comment]
Hi @swiatekm-sumo . Thank you for the reply. Also, thanks for the tip on the kubernetes-sumologic plugin. I was using the `kubernetes_metadata_filter` to pull in that K8s data above, but it looks like this might be a little cleaner solution. I'll go ahead and close this issue.
